version: "3.3"
services: 
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./videapp.json:/usr/lib/VideRest/videapp.json
    environment: 
      - SWAGGER_JSON=/usr/lib/VideRest/videapp.json
